package mail_app.exception;

public enum ServerErrorCode {
    DATABASE_EXCEPTION,
    NOT_READABLE_MESSAGE,
    POST_OFFICE_NOT_FOUND,
    POST_MAILING_NOT_FOUND,
    ALREADY_ARRIVED,
    ALREADY_ON_WAY,
    NOT_RECIPIENT_POST_OFFICE

}
